export const ROUTES = {
  EMPTY: '/empty',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  REGISTRATION_ARRIVAL: '/registration/arrival',
  REGISTRATION_DEPARTURE: '/registration/departure',
  HISTORY: '/history',
  REPORTS: '/reports',
  REPORTS_COUNTERPARTIES: '/reports/counterparties',
  REPORTS_STATISTICS: '/reports/statistics',
  DICTIONARY: '/dictionary',
  DICTIONARY_COUNTERPARTIES: '/dictionary/counterparties',
  DICTIONARY_VEHICLES: '/dictionary/vehicles',
  DICTIONARY_CONTRACTS: '/dictionary/contracts',
  DICTIONARY_SERVICES: '/dictionary/services',
}
